### ISSUE TITLE
Let your tests run on travis-ci.

### ISSUE THREAD

**Issue by h4cc** [1up-lab/contao-security-advisories#1]
I see you have tests. How about running them automatically with travis-ci ?

Example configuration: https://gist.github.com/h4cc/9141671#file-travis-template-with-hhvm-as-allowed-failure-yml

**Comment by bytehead** [comment]
There are tests yes, actually more skeleton than real test.
They are a bit useless at the moment, so we didn't set up a travis env so far.

**Comment by sheeep** [comment]
We'll consider this if we ever find the time to write proper tests ;)
